name: "Called"

on:
  workflow_call:
    inputs:
      container:
        required: false
        default: master
        type: string
      suite:
        required: true
        type: string
      pkg:
        required: true
        type: string

jobs:
  called:
    name: "Hey ${{ matrix.container }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ${{fromJson(inputs.container)}}
    steps:
      - run: echo ${{ matrix.container }}
      - run: echo ${{ inputs.suite }}
      - run: echo ${{ inputs.pkg }}
