name: "Name of caller Workflow file"

on:
  push:

jobs:
  caller:
    #strategy:
    #  matrix:
    #    container:
    #      - master
    #      - stable-4.11
    uses: wilfwilson/experimenting/.github/workflows/called.yml@master
    name: "Name of caller job"
    with:
      container: >-
        ["master", "stable-4.11"]
      suite: >-
        ["testinstall", "testbugfix", "teststandard"]
      pkg: >-
        ["no", "auto", "all"]
