name: "Name of caller Workflow file"

on:
  push:

jobs:
  caller:
    uses: ./.github/workflows/called.yml
    name: "Name of caller job"
    with:
      container: >-
        ["master", "stable-4.11"]
      suite: >-
        ["testinstall", "testbugfix", "teststandard"]
      pkg: >-
        ["no", "auto", "all"]
