name: "Name of called Workflow file"

on:
  workflow_call:
    inputs:
      container:
        required: true
        type: string
      suite:
        required: true
        type: string
      pkg:
        required: true
        type: string

jobs:
  called:
    name: "Name of called job: ${{ matrix.container }} / ${{ matrix.suite }} / ${{ matrix.pkgs }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: ${{ fromJson(inputs.container) }}
        suite:     ${{ fromJson(inputs.suite) }}
        pkgs:      ${{ fromJson(inputs.pkg) }}
    steps:
      - run: echo ${{ matrix.container }}
      - run: echo ${{ matrix.suite }}
      - run: echo ${{ matrix.pkgs }}
