name: "Hey"

on:
  push:

jobs:
  caller:
    strategy:
      matrix:
        container:
          - master
          - stable-4.11
    uses: wilfwilson/experimenting/.github/workflows/called.yml@master
    with:
      container: ${{ matrix.container }}
      suite: testinstall
      pkg: digraphs
