name: "Dynamic matrix"

on:
  push:

jobs:
  gapcontainer:
    name: "Container job"
    runs-on: ubuntu-latest
    container: ghcr.io/gap-system/gap-docker-master:master
    steps:
      - run: pwd
      - run: printenv
      - run: which gap
      - run: /home/gap/inst/gap-master/bin/gap.sh --version
      - uses: actions/checkout@v2
