name: "Dynamic matrix"

on:
  push:

jobs:
  gapcontainer:
    name: "Container job"
    runs-on: ubuntu-latest
    container: ghcr.io/gap-system/gap-docker-master:master
    steps:
      - run: pwd
      - run: which gap
      - run: /bin/sh -c "gap --version"
      - uses: actions/checkout@v2
